### ISSUE TITLE
Fix Scrolling Behavior

### ISSUE THREAD

**Issue by demonslayer147** [Ktar5/Info-Board#1]
Is there anyway you can fix the scrolling? Right now in the lastest version scrolling does not support color and it doesnt behave like it does
What i mean by behave was like this>

Config>
Info Board:
  '1':
    Show Time: 1
    world:
      default:
        Title: '&2[factionsfname]'
        Rows:
        - '&4[nuke]----[skull]----[nuke]'
        - '&9&lFaction Power:'
        - [factionsfpower]/&f[factionsfmaxpower]
        - '&9&lPower:'
        - [factionspower]/[factionsmaxpower]
        - '[scroll]This is not a correct line to display'   < Scrolling section
        - '&cStanding in> &e[factionsfinname]'

Display> Please look at the animation attached
![capture](https://cloud.githubusercontent.com/assets/6226252/6998271/9acbedd2-db8f-11e4-9911-cd2cb2222287.gif)

P.S: GitHub doesnt allow me to put < > in here i replaced [ ] instead to all variable

**Comment by Ktar5** [comment]
Hmm.. that is quite interesting.. I shall fix in the next one or two days.

**Comment by pixar02** [comment]
We think it's fixed! try out our newest version and let us now if the problem is still occuring
