### ISSUE TITLE
Infoboard not working with new WorldGuard 1.8+

### ISSUE THREAD

**Issue by jparrack** [Ktar5/Info-Board#10]
Hi guys, sorry to bother you all. We have just installed InfoBoard Reloaded 1.7.0 onto our server running 1.8 alongside WorldGuard. I have seen other people comment about this and they are saying that InfoBoard is not starting due to WorldGuard. I have checked the logs on the server and this appears to be the issue. 

Since I am fairly new to this, I was just wondering how I could get Infoboard Reloaded to start alongside WorldGuard.

Thanks, JParrack

**Comment by pixar02** [comment]
This is Fixed.
bit.ly/InfoBoardReborn_bukkit
