### ISSUE TITLE
Error Message on Startup

### ISSUE THREAD

**Issue by Techno3600** [Ktar5/Info-Board#101]
Here it is.
![img_1038](https://cloud.githubusercontent.com/assets/26912279/24684317/104765b4-1973-11e7-8a97-e3768746a998.PNG)
![img_1039](https://cloud.githubusercontent.com/assets/26912279/24684318/105731a6-1973-11e7-8df0-99db373d418a.PNG)
![img_1040](https://cloud.githubusercontent.com/assets/26912279/24684319/1057d4f8-1973-11e7-9008-dcd06edaf6ce.PNG)

**Comment by dotpkg** [comment]
you don't have vault installed.

**Comment by Techno3600** [comment]
Why would you need vault?

**Comment by Techno3600** [comment]
Is it required?

**Comment by mtaheij** [comment]
Yes, it's required to have vault installed.

**Comment by pixar02** [comment]
https://www.spigotmc.org/resources/infoboardreloaded.44270/
