### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Techno3600** [Ktar5/Info-Board#102]
When I try to do a command from both the console and in-game it responds with /ib every time and nothing happens.

Thanks
Anand

**Comment by Techno3600** [comment]
I installed vault and it still doesn't work,

Same kind of message. Maybe try giving me a link to the vault I should use?
Is it required to have Vault, I really don't want it.

**Comment by pixar02** [comment]
IB doesn't work, try using this: bit.ly/InfoBoardReloaded
