### ISSUE TITLE
New Part of Config

### ISSUE THREAD

**Issue by Techno3600** [Ktar5/Info-Board#103]
There should be a line in the next update called "Use Vault", so we can disable it if needed

**Comment by pixar02** [comment]
Why would you not want it?
A good server has 90% chance to have vault installed... Just because there permissions plugin can communicate with the economy plugin.

**Comment by Techno3600** [comment]
I wrote this a LONG time ago, I have Vault.

**Comment by pixar02** [comment]
Could you close this then ?
