### ISSUE TITLE
Health Bar

### ISSUE THREAD

**Issue by JOthePRO45** [Ktar5/Info-Board#104]
This is a fantastic plugin! Only one problem. While this plugin is installed, my health bar plugin does not work. I want my health bar to appear below players names, but while i have this plugin installed, it doesn't work. (Neither does the vanilla command work).

Please fix or let me know what I am doing wrong. 

Thanks!!

**Comment by pixar02** [comment]
We now the issue and are already working on a possible solution. Stay tuned for more info about it. Make sure you have the latest version ! Link to recource: bit.ly/InfoBoardReborn_bukkit
