### ISSUE TITLE
What is the % thing to let the player see  how much money,kills,deaths the player has 

### ISSUE THREAD

**Issue by Trae66** [Ktar5/Info-Board#109]
im trying to figure out if its like %kills% or %deaths% or %balance% or %money% ya know what i mean?

**Comment by pixar02** [comment]
For Deahts and kills,it's statistics. for money or balance it is vault.
For all the statistics placeholders use this link: https://www.spigotmc.org/wiki/placeholderapi-placeholders/
for all vault's placeholders use this link: https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-1/

There are more placeholders the your asking for. The easiest way to find them is to search for them, Chrome let's you do that by "Ctrl+f" and type the word you want.

**Comment by Trae66** [comment]
Thanks!
