### ISSUE TITLE
Error Paper Spigot 1.12, Java 8. 

### ISSUE THREAD

**Issue by TheIntelloBox** [Ktar5/Info-Board#110]
https://hastebin.com/umovakifaj.css

**Comment by pixar02** [comment]
We know the bug. We are trying to fix it as we speak

**Comment by pixar02** [comment]
Update is available, you can download it at: [Spigot](bit.ly/InfoBoardReborn_spigot) or [Bukkit](bit.ly/InfoBoardReborn_bukkit)
