### ISSUE TITLE
Issue when I put 3 scoreboards.

### ISSUE THREAD

**Issue by TheIntelloBox** [Ktar5/Info-Board#111]
I don't see the third scoreboard : https://hastebin.com/furiqeriwi.php

**Comment by pixar02** [comment]
Are there any errors in console?
Did you reload the server after you created the third board?

**Comment by TheIntelloBox** [comment]
0 error and I restarted the server.

**Comment by pixar02** [comment]
I tested your board.yml file and it works fine. I'm using: 

- IBR-2.0.2 
- PlaceholderAPI-2.8.2
- EssentialsX-2.0.1
- Vault-1.5.6
- WorldGuard-6.2.1
- WorldEdit-6.1.7.2
- LuckPerms-3.2.20

**Comment by TheIntelloBox** [comment]
The problem was autorank's placeholder.

**Comment by pixar02** [comment]
So everything works? (close this issue then, pls)
