### ISSUE TITLE
New version available whereas I have changed the version.

### ISSUE THREAD

**Issue by TheIntelloBox** [Ktar5/Info-Board#112]
Hey,

I'm using V2.0.2 and the plugin says "New version available" whereas I have changed the version.

Thanks.

**Comment by pixar02** [comment]
We are aware about this bug/glitch it's a problem on the websites end. We will try to find a solution. If you dislike the message you can disable it in the config file.

**Comment by pixar02** [comment]
Fix in upcomming update! Stay tunned for it!

**Comment by pixar02** [comment]
Update is available, you can download it at: [Spigot](https://bit.ly/InfoBoardReborn_spigot) or [Bukkit](https://bit.ly/InfoBoardReborn_bukkit)
