### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by boynextdoorqwq** [Ktar5/Info-Board#114]
01.02 10:07:52 [Server] INFO java.lang.NullPointerException
01.02 10:07:52 [Server] WARN Task #53818 for InfoBoardReborn v2.0.2 generated an exception
01.02 10:07:52 [Server] INFO java.lang.NullPointerException
01.02 10:07:52 [Server] WARN Task #53818 for InfoBoardReborn v2.0.2 generated an exception
01.02 10:07:52 [Server] INFO java.lang.NullPointerException
01.02 10:07:52 [Server] WARN Task #53817 for InfoBoardReborn v2.0.2 generated an exception
01.02 10:07:52 [Server] INFO java.lang.NullPointerException
01.02 10:07:52 [Server] WARN Task #53818 for InfoBoardReborn v2.0.2 generated an exception
01.02 10:07:52 [Server] INFO java.lang.NullPointerException
01.02 10:07:52 [Server] WARN Task #53818 for InfoBoardReborn v2.0.2 generated an exception
01.02 10:07:52 [Server] INFO java.lang.NullPointerException
01.02 10:07:52 [Server] WARN Task #53818 for InfoBoardReborn v2.0.2 generated an exception
01.02 10:07:52 [Server] INFO java.lang.NullPointerException
01.02 10:07:52 [Server] WARN Task #53818 for InfoBoardReborn v2.0.2 generated an exception
01.02 10:07:52 [Server] INFO java.lang.NullPointerExc

**Comment by pixar02** [comment]
Could you send the entire console log? With this we can't help...
