### ISSUE TITLE
AutoRank : %autorank_time_of_player%

### ISSUE THREAD

**Issue by TheIntelloBox** [Ktar5/Info-Board#115]
Hey ! :D

The placeholder of AutoRank : %autorank_time_of_player% is useless because on my scoreboard the time played is in seconds... So I have 7000000 seconds... How can I change that ? :D

Thanks ! :D

**Comment by pixar02** [comment]
What version of the expansion are you using?

**Comment by pixar02** [comment]
What version of the expansion are you using?
Also I will try to speak with the author of the expansion to see if he can make a formated version of what you want.. @extendedclip

**Comment by extendedclip** [comment]
I will add a placeholder for autorank which displays  formatted time played. tomorrow

**Comment by pixar02** [comment]
Thanks Clip!

**Comment by extendedclip** [comment]
https://api.extendedclip.com/expansions/autorank/versions/autorank-102/

%autorank_time_of_player_formatted%

**Comment by pixar02** [comment]
@TheIntelloBox use the above given link to get a new version of expansion and with that use: %autorank_time_of_player_formatted% to get a formated version of %autorank_time_of_player%

**Comment by TheIntelloBox** [comment]
When will it be added to Placeholder API ?

**Comment by TheIntelloBox** [comment]
I installed it but doesn't work. @extendedclip

**Comment by pixar02** [comment]
The expansion is not a plugin. You have to put the jar file in: \plugins\PlaceholderAPI\expansions
