### ISSUE TITLE
Task 809.

### ISSUE THREAD

**Issue by TheIntelloBox** [Ktar5/Info-Board#120]
https://hastebin.com/moyulidica.vbs

**Comment by pixar02** [comment]
What permission plugin are you using?

**Comment by TheIntelloBox** [comment]
LuckPerms.

**Comment by pixar02** [comment]
Could you send your config and your board file pls?

**Comment by TheIntelloBox** [comment]
Hi ! :D

Sorry for the delay ! :D 

Config.yml : https://hastebin.com/kaxutayiho.php ! :D 
Boards.yml : https://hastebin.com/kuyogakira.php ! :D 

Thanks ! :D

**Comment by pixar02** [comment]
Just checking if you still have this error? 
If not I will close this issue (will reop if it happens again)

**Comment by TheIntelloBox** [comment]
Nop. :)
