### ISSUE TITLE
console task spam

### ISSUE THREAD

**Issue by justinbea** [Ktar5/Info-Board#122]
https://pastebin.com/49haqewx

**Comment by justinbea** [comment]
permissionsex

**Comment by pixar02** [comment]
Could you send your Board.yml file please?

**Comment by justinbea** [comment]
`# InfoBoardReborn Board file
# ===============================================================================================
# |                               Max Rows for a board is 15                                    |
# |                            Max characters for a title is 32                                 |
# |                             Max characters for a line is 48                                 |
# |---------------------------------------------------------------------------------------------|
# |               When using scroll there is no limit for characters per line                   |
# |=============================================================================================|
# |=============================================================================================|
# |                                        Example                                              |
# |---------------------------------------------------------------------------------------------|
# |InfoBoard:                                                                                   |
# |  '1':                                                                                       |
# |    ShowTime: 10                                           # How Long this page is shown for |
# |    global:                                        # What world sees this page (global = All)|
# |      default:                        # What Permissions group sees this page (default = All)|
# |        Title: '&4&lKtarLalaLand'                                                            |
# |         Rows:                                                                               |
# |         - ' '                                                                               |
# |         - 'This board is seen by everyone'                                                  |
# |         - 'That isn''t in Admin'                                                            |
# |      Admin:                                                                                 |
# |        Title: '&4&lAdmin Page'                                                              |
# |        Rows:                                                                                |
# |        - ' '                                                                                |
# |        - 'This board is only'                                                               |
# |        - 'seen by Admins'                                                                   |
# |  '2':                                                                                       |
# |    ShowTime: 5                                                                              |
# |    world:                                                                                   |
# |      default:                                                                               |
# |        Title: '&a&lStats'                                                                   |
# |         Rows:                                                                               |
# |         - 'Online Players: ; %server_online%'      # Splitting a line can be done by using ;|
# |         - 'Money: ; %vault_eco_balance%'                                                    |
# |    world_the_nether:                                                                        |
# |      default:                                                                               |
# |        Title: '&a&lNether'                                                                  |
# |         Rows:                                                                               |
# |         - 'Your Level:'                                                                     |_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
# |         - '~!%player_level%' # Will only display if %player_level% isn't "0" or "Unknown" or one of many other empty values |
# ===============================================================================================================================
InfoBoard:
  '1':
    ShowTime: 10
    global:
      default:
        Title: '&3Welkom op RifleGames!'
        Rows:
        - '&b--=&7RifleGames&b=--'
        - ' '
        - '&3&lWelcome!'
        - '&b%player_name%'
        - ' '
        - '&3&lYou played:'
        - '&b%statistic_days_played_remaining%d %statistic_hours_played_remaining%h %statistic_minutes_played_remaining%m'
        - ' '
        - '&3&lMoney:'
        - '&b%vault_eco_balance%'
        - ' '
        - '&b--=&7RifleGames&b=--'
  '2':
    ShowTime: 10
    global:
      default:
        Title: '&4Welkom op RifleGames!'
        Rows:
        - '&4&lYour reputation:'
        - '&c%pvptitles_rank%'
        - ' '
        - '&4&lPlayer Kills:'
        - '&c%statistic_player_kills%'
        - ' '
        - '&4&lWalker Kills:'
        - '&c%statistic_kill_entity_ZOMBIE%'
        - ' '
        - '&4&lDeaths:'
        - '&c%statistic_deaths%'
        - '&4--=&7RifleGames&4=--'`

**Comment by justinbea** [comment]
hello?

**Comment by justinbea** [comment]
hello2?

**Comment by pixar02** [comment]
It looks like Vault is acting strange... I will see what I can do about it but it is something strange...
Just on a sidenote, does the board still work? So I can put it on a priority list...

**Comment by justinbea** [comment]
ive removed the .jar file out of the server of the spam and cpu usage of it. so no
