### ISSUE TITLE
1.13 compatible.

### ISSUE THREAD

**Issue by TheIntelloBox** [Ktar5/Info-Board#126]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/

**Comment by pixar02** [comment]
We know that there are some PRE-builds... I haven't had the time to look into it yet. Hope to get it updated with the new version.

**Comment by TheIntelloBox** [comment]
Hey ! 1.13 is released. :)

**Comment by TheIntelloBox** [comment]
@pixar02 Did you work on it ? :)

**Comment by pixar02** [comment]
I am, along with some other bug fixes....

**Comment by pixar02** [comment]
Technically, it works for 1.13. But  for some reason there are some bugs occurring with the colors....
When you apply a color  with the "&" it should color everything that comes after it until you change it again... for some reason it stops half way the string and resets the color...
When that is fixed I will release an update. I hope to get it done at the end of next week.

**Comment by TheIntelloBox** [comment]
I saw that you closed the issue so the release is done ? :)

**Comment by pixar02** [comment]
I fixed the bug, for 1.13 Still trying to fix al the other bugs though... the sourcecode is open so if you pull it you could build the plugin yourself...

**Comment by TheIntelloBox** [comment]
Have you got an estimated date ? :D
