### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by myyris** [Ktar5/Info-Board#137]
Hi. I have no idea why, but this plugin is not working for me. I put it into the plugins folder and restart the server, but nothing happens. It shows up in my FTP but not in the game. Every other plugin has worked for me but this. I've tried every version and everything, but this plugin just doesn't work in my server. And it's not just this server. I've had servers even before and this has been the only plugin not working. Please tell me if i'm doing something wrong. And no comments like "Are you absolutely sure that you put them into the plugins folder?" Yes. I am sure. pls help meh

**Comment by pixar02** [comment]
What server version are you using?
Did you download the dependencies? (Vault, PlaceholderAPI, WorldGuard AND ANY economy plugin)
Also are there any errors in the console?

**Comment by 1tarnicol1** [comment]
Hey, pixar ! I have a problem! In minecraft there are no indicators on the information panel, but only the code for them. for example, < %player_name%>. I have no mistakes.

**Comment by 1tarnicol1** [comment]
I found a solution to the problem! Sorry to bother you! The problem was solved by the team / papi cloud download player! Your plugin is just super! Good luck!
