### ISSUE TITLE
scrolling text do not work

### ISSUE THREAD

**Issue by Theprim0** [Ktar5/Info-Board#138]
Just a clear installation and only setting Scrolling to enable and put a line with:
- '<scroll> Hello World!'

Doesn't work

**Comment by pixar02** [comment]
Read this section: https://github.com/Ktar5/Info-board/wiki/Basics#scrolling-text 
If it still doesn't work, could you send me the config.ml and Board.yml file?

**Comment by Theprim0** [comment]
[conf and board.zip](https://github.com/Ktar5/Info-Board/files/2659967/conf.and.board.zip)

There they are, i just enabled the scollable text in config.yml and put a line with <scroll> Hello Word, is this working? ..... in board.yml

I'm using spigot 1.8.8

**Comment by pixar02** [comment]
Is the scoreboard working? Is there a board? If not make sure you have PlaceholderAPI, Vault, WorldGuard and an economy plugin installed.

**Comment by pixar02** [comment]
What version of the plugin are you using ?

**Comment by Theprim0** [comment]
infoboard-2.0.4.jar

The latest one. Downloaded from your spigotmc.org official page

**Comment by pixar02** [comment]
I ran you configuration and it appears to be a bug of some kind. I would suggest that you use 2.0.3 since it does work in that version. I will get to fix it soon.

**Comment by Theprim0** [comment]
I didn't even thought about use a older version. Well in the older it works, i will use that one. At least you know it doen't work in the latest one haha. Keep on
BTW NICE PLUGIN. +1
