### ISSUE TITLE
Paper Compatible?

### ISSUE THREAD

**Issue by briankmco** [Ktar5/Info-Board#142]
I get this error on server startup:
23.03 11:31:22 [Server] ERROR Could not load 'plugins/infoboard-2.0.4.jar' in folder 'plugins'
23.03 11:31:22 [Server] INFO org.bukkit.plugin.UnknownDependencyException: WorldGuard
23.03 11:31:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) ~[patched_1.13.2.jar:git-Paper-566]
23.03 11:31:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-566]
23.03 11:31:22 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-566]
23.03 11:31:22 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-566]

**Comment by briankmco** [comment]
I forgot to mention that I do not use Worldguard

**Comment by pixar02** [comment]
WorldGuard is a must... The downside is Worldguard for 1.13.X works but not like it used to, and what this plugin needs form it is no longer available...

**Comment by pixar02** [comment]
I will update the plugin for 1.13.X but without the WorldGuard features...
