### ISSUE TITLE
Create a variable to show other servers player counters inside a Bungeecord server

### ISSUE THREAD

**Issue by Gimmoh** [Ktar5/Info-Board#145]
I would like to get this feature added to the plugin, it's really useful and could make my scoreboard look cooler. it's also useful to show that on a certain server there are tons of people having fun :3

Thanks in advice.

**Comment by Gimmoh** [comment]
This could be used for a bungee server.

**Comment by pixar02** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bungeecord
