### ISSUE TITLE
Problem with donate

### ISSUE THREAD

**Issue by Miyasha** [Ktar5/Info-Board#149]
Faced a problem. On the server does not want to show the player’s donate in the table. Take it easy code.
![2019-05-13_07 11 22](https://user-images.githubusercontent.com/50554458/57595602-be2c8b80-754e-11e9-9571-c37fbcfadd4a.png)

**Comment by pixar02** [comment]
%rank% is not a valid placeholder.
Please read this page for info about the placeholders: https://github.com/Ktar5/Info-Board/wiki/Old-Version

**Comment by pixar02** [comment]
I think the best placeholder for that rank is: %vault_rank%

**Comment by Miyasha** [comment]
And you can make it so that it shows the prefix of the privilege, and not the name?

**Comment by Miyasha** [comment]
Thank you already found and decided!
