### ISSUE TITLE
Using 1.7.10 getting a large Stack Trace

### ISSUE THREAD

**Issue by Vidsify** [Ktar5/Info-Board#15]
Hello,

I go to do /infoboard reload and get this. Also the scoreboard is not showing up!!
http://pastebin.com/rwfm1f2L

Thanks

**Comment by suaykepier** [comment]
I had the same issue, the solution is to update your worldguard plugin for the last version ^^

**Comment by Vidsify** [comment]
Oh ok I thought my world guard was the latest version. I'll try it thanks
