### ISSUE TITLE
My server can't install this plugin

### ISSUE THREAD

**Issue by KimTung501** [Ktar5/Info-Board#161]
I've found this plugin when i'm searching youtube with hope i can find some plugins really cool and useful for my server 
    I installed this plugins but when I open my server, i can't use any command in plugin so i checked my list of plugin was running in server and i saw infoboardreborn did not accpect
   And in the console windows, it said "Cannot execute command 'ibr' in plugin InfoBoardReborn v2.0.6 - plugin is disabled."

**Comment by pixar02** [comment]
IBR needs PlaceholderAPI for it to work check the download page or the [wiki](https://github.com/Ktar5/Info-Board/wiki/Installation-(New))
