### ISSUE TITLE
[Enhancement] ASkyblock Support

### ISSUE THREAD

**Issue by Cmoor** [Ktar5/Info-Board#19]
Hi there, i really love the look of this plugin and wish to use it on my skyblock server and i use ASkyblock by tastybento. i cannot part with this one for how much i have used it but i would like a request for the island level support and maybe the number of challenges complete if possible? Thanks in advance!

**Comment by Cmoor** [comment]
Yes? No? Maybe so?

**Comment by 8972legand** [comment]
I also agree :P
