### ISSUE TITLE
InfoBoard Bug

### ISSUE THREAD

**Issue by byAeeder** [Ktar5/Info-Board#2]
Hey, i'm getting an issue with the Board, i got the <scroll> variable in my server, but when i log in the board starts bugging, here's a gif http://gyazo.com/a73b5b68321e37334859da7a82c99c60

**Comment by byAeeder** [comment]
By the way, im not getting any error in the console

**Comment by Ktar5** [comment]
Marked as duplicate #1

**Comment by byAeeder** [comment]
What does duplicated mean?

**Comment by Ktar5** [comment]
It means that this is a duplicate bug report, check issue #1
