### ISSUE TITLE
Scrolling Text Issue (Urgent Help)

### ISSUE THREAD

**Issue by SmokierDrop** [Ktar5/Info-Board#21]
This is My Code:
  '1':
    Show Time: 1
    HUB:
      default:
        Title: [scroll]&f&lWelcome [player] to [servername] 
        Rows:
        - '&b&lServer:'
        - [worldname]
        - ' '
        - '&a&lCoins:'
        - [money]
        - ' '
        - '&6&lRank:'
        - [rank]
        - ' '
        - '&e&lLevel:'
        - [level]
        - ' '
        - '&c&lWebsite:'
        - [website]
        - '&l---------------'
When I reload the board an look at the title it goes bold while showing the color code and then suddenly changes its font to the normal size... I really need help tot fix this.
![2015-05-18_15 16 04](https://cloud.githubusercontent.com/assets/12492047/7675947/56fdec14-fd71-11e4-94b0-91fb29e123e8.png)
![2015-05-18_15 16 07](https://cloud.githubusercontent.com/assets/12492047/7675976/b43f3b08-fd71-11e4-8137-a29223db8735.png)
![2015-05-18_15 16 09](https://cloud.githubusercontent.com/assets/12492047/7675977/b6b65542-fd71-11e4-86b1-76113ed3b303.png)
![2015-05-18_15 16 18_5](https://cloud.githubusercontent.com/assets/12492047/7675979/b8e22bde-fd71-11e4-8181-12fce6035113.png)
I replaced <> with [] cause of git hub policies.

**Comment by chillerkraft** [comment]
i had this issue posted here too.
someone decided to just close it without saying anything to me..
https://github.com/Ktar5/Info-Board/issues/12
i guess they didn't feel like admitting that they cant fix it?

**Comment by PrimeRobotMC** [comment]
In the config.yml file, it says formats aren't supported yet, at least for me it does.

**Comment by chillerkraft** [comment]
o ty
