### ISSUE TITLE
Major Errors With Plugin

### ISSUE THREAD

**Issue by O4MicahO4** [Ktar5/Info-Board#22]
The Console Says This Without Me Doing Anything, it just says this repeating, also the scoreboard won't show when I do /ib show, It does says its now hidden anymore and doesn't do anything else.

18.05 22:53:48 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:48 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:48 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:48 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:48 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:48 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:48 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:48 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:48 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:48 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:48 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:46 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:46 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:46 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:46 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:46 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:46 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:46 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:46 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:46 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:46 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:46 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:46 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:46 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:44 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:44 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:44 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:44 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:44 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:44 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:44 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:44 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:44 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:44 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:44 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:44 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:44 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:42 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:42 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:42 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:42 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:42 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:42 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:42 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:42 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:42 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:42 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:42 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:40 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:40 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:40 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:40 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:40 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:40 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:40 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:40 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:40 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:40 [Server] INFO at com.ktar5.infoboard.Timers$1.run(Timers.java:90) ~[?:?] 18.05 22:53:40 [Server] INFO at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:25) ~[?:?] 18.05 22:53:40 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:40 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:40 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:40 [Server] WARN Task #84 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:38 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:38 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:38 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:38 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:38 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:38 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:38 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:38 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:38 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:38 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:38 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:36 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:36 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:36 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:36 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:36 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:36 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:36 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:34 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:34 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:34 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:34 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:34 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:34 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:34 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:34 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:34 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:34 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:34 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:32 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:32 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:32 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:32 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:32 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:32 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:32 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:32 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:32 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:32 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:32 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:30 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:30 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:30 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:30 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:30 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:30 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:30 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:30 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:30 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:30 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:30 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:30 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:30 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:28 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:28 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at com.ktar5.infoboard.Timers$1.run(Timers.java:90) ~[?:?] 18.05 22:53:28 [Server] INFO at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:25) ~[?:?] 18.05 22:53:28 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:28 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:28 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:28 [Server] WARN Task #84 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:28 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:28 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:28 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:28 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:28 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:28 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:28 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:28 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception 18.05 22:53:26 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 18.05 22:53:26 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:26 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:26 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:26 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:26 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:26 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot183.jar:git-Spigot-26dfd01-5cb9b70] 18.05 22:53:26 [Server] INFO at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] 18.05 22:53:26 [Server] INFO at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:51) ~[?:?] 18.05 22:53:26 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:23) ~[?:?] 18.05 22:53:26 [Server] INFO at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:42) ~[?:?] 18.05 22:53:26 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected 18.05 22:53:26 [Server] WARN Task #85 for InfoBoardReborn v1.7.0 generated an exception

**Comment by duuhnuts** [comment]
Try updating to the latest Spigot version and update to latest InfoBoardReborn jar.
