### ISSUE TITLE
Needs 1.8 Update

### ISSUE THREAD

**Issue by xAcrosonicx** [Ktar5/Info-Board#25]
I'm sure many of the players who use this plugin are using 1.8 or above. I am currently running 1.8.3 and getting all sorts of errors, and would really appreciate it if you updated! It's a fantastic plugin

**Comment by duuhnuts** [comment]
This plugin supports 1.8 and above, and the developer is very busy. Im sure he has some other important things to take care of, if you do have any Java knowledge, maybe you could decomplice  and update it yourself?
