### ISSUE TITLE
Not showing

### ISSUE THREAD

**Issue by michal12sk** [Ktar5/Info-Board#26]
My infoboard in not showing and when i do /ib reload it says Configs been reloaded and then  it says An internal error occurred while attemping to perform this command. And this is console : http://pastebin.com/PFLZgQUb

**Comment by duuhnuts** [comment]
Try to update to the latest Spigot version, Assuming you have BuildTools on your desktop, Go on cmd, then do cd /Desktop/ then do java -jar BuildTools.jar and let it run. Then use that jar generated, and see if it fixes it.
