### ISSUE TITLE
<direction> 90 degrees off

### ISSUE THREAD

**Issue by impatman** [Ktar5/Info-Board#27]
As shown in the picture I'm facing west but it is showing that I'm facing north. Seems like it is consistently 90 degrees off.
![image](https://cloud.githubusercontent.com/assets/12699181/8244304/5eeacdfe-15ed-11e5-9c37-1e0d2546d813.png)

**Comment by duuhnuts** [comment]
Please paste in the configuration, It seems like there is a error in your configuration,

**Comment by impatman** [comment]
Info Board:
  '1':
    Show Time: 5
    world:
      default:
        Title: '&lWelcome To MazeCraft'
        Rows:
        - '&a&lYou are in:'
        - '&e<worldguardinid>'
        - ' '
        - '&5&lRank:'
        - <rank>
        - ' '
        - '&5&lDirection:'
        - '&a<direction>'


It's a problem with the math. I already forked it and fixed it. See: https://github.com/Ktar5/Info-Board/pull/32
