### ISSUE TITLE
This internet Minecraft thingy ain't workin

### ISSUE THREAD

**Issue by 21stMC** [Ktar5/Info-Board#29]
Her ner. Ir hars aready reads this threads and all, but this pluger-in says it is workin and twerkin all over 1.7.10 and 1.8.1, but my Spigots is workingses on 1.8.5, and it ain't working there. Whta is going on? Confederates! F*ck yearh!

**Comment by duuhnuts** [comment]
Please could you give me a stacktrace of the error login in the console? This is vital for us to resolve your issue, and please keep the swearing down to a minimum.
