### ISSUE TITLE
Scoreboard flash

### ISSUE THREAD

**Issue by Lemrigue** [Ktar5/Info-Board#3]
The variable "heroespartyleader" (plugin Heroes) doesn't work, it wrote com.herocraftonline.heroes instead of the name of the party leader.
A screen : 
![ss 2015-04-17 at 02 57 04](https://cloud.githubusercontent.com/assets/11993172/7202479/ffebc4f8-e512-11e4-8920-92c1eb0d3324.png)

**Comment by Lemrigue** [comment]
My bad, plugin was in conflict with infernalMobs

**Comment by Ktar5** [comment]
Hmm, well, ill try to get into contact with the hero plugin's devs to get something worked out, I'm implementing a new system
