### ISSUE TITLE
[FEATURE REQUEST] Countdown

### ISSUE THREAD

**Issue by dsilvaevje99** [Ktar5/Info-Board#33]
Could you add a countdown function? As a variable maybe, for example if you put countdown:30d on a line it will start counting down from whatever you put. And also add a way to decide what happens when the countdown is over, if to renew it or remove the line or something.

This would be really useful for events happening on my server :)

THANKS!

**Comment by TheIntelloBox** [comment]
It would be great omg ! :D

**Comment by pixar02** [comment]
The server Expansino has a countdown. "%server_countdown_<SimpleDateFormat>_<time>%" https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#Server
