### ISSUE TITLE
Task 80 and 81, Stats variables.

### ISSUE THREAD

**Issue by AnonymousMW3** [Ktar5/Info-Board#40]
Hello,
I am using this plugin with stats variables but i get errors in console from infoboardreborn.
Here you can find the errors: 
http://pastebin.com/gBdrAVZS

Board doesn't work, please say me how to fix this problem.
Stats work correctly.
Thanks :)

**Comment by JACQUEECE** [comment]
I get the same error when hooking in pvpstats and Stats3, the board just dissapears all together.

**Comment by AnonymousMW3** [comment]
Me too with pvpstats.
Please update the plugin!

**Comment by mb1552** [comment]
Please, this would make me 100% on the plugin!
