### ISSUE TITLE
[Is This Possible] Per World Scoreboard

### ISSUE THREAD

**Issue by 8972legand** [Ktar5/Info-Board#42]
Hey! Just wondering is there any support for multiple worlds? Like a scoreboard for OPPrison and a Scoreboard for Prison and a Scoreborad for Factions is that possible? To have different scoreborads per worlds?

**Comment by michal12sk** [comment]
yes it is. You have numbered the scoreboards 1 and 2. If you want  to make it per world you just need to rewrite that or create new that is with WorldName instead of the numbers

**Comment by 8972legand** [comment]
Ah lol thanks!
