### ISSUE TITLE
Suggestion new variable / Plugin Quests

### ISSUE THREAD

**Issue by Lemrigue** [Ktar5/Info-Board#5]
Hello, your scoreboard plugin is surely one of the best and I would like to know if it possible to add new variables. I use Quests plugin (http://dev.bukkit.org/bukkit-plugins/quests/) and I would like to know if it is possible to add variables like the name of the quests or if we have a quests or how many quests are done, etc.
Thanks to read it

**Comment by Ktar5** [comment]
Soon there will be a API for plugin developers to add their own variables! So let's wait for that :)
