### ISSUE TITLE
What is wrong with my config?

### ISSUE THREAD

**Issue by DiamondPigman** [Ktar5/Info-Board#55]
Ever since I changed my scoreboard from default to my own, whenever I reload infobaord (/infoboard reload) it greets me with "An internal error occurred while attempting to perform this command"
I was wondering if i was my custom board that broke it.. 
![infoboard board](https://cloud.githubusercontent.com/assets/14424577/9982813/0fa3fef4-5fe0-11e5-8328-bb5841c89f30.png)

**Comment by t5r7** [comment]
Never mind! Got it working :)

Update seven years later: it looks like it was a stray single quote on line 52.
