### ISSUE TITLE
Variable Request - Worldborder

### ISSUE THREAD

**Issue by ProfessorKappa** [Ktar5/Info-Board#87]
This is a request for a Vanilla variable to show the size of the current Vanilla worldborder. 

It could be implemented in may ways, whether it be the total border (<worldborder>) or per coordinate, (<worldborderX> and <worldborderZ>), which I suggest the most. Thank you!

**Comment by AmecGamer** [comment]
I also need this variable Help :)

**Comment by pixar02** [comment]
I made an expansion for it. Everything is explained on the resource page: https://www.spigotmc.org/resources/worldborder-expansion.57000/
