### ISSUE TITLE
PlotSquared Support

### ISSUE THREAD

**Issue by FinnehPleh** [Ktar5/Info-Board#88]
Just wondering if there is a way to get PlotSquared support for the plugin.
I love the plugin, using it on all of my servers but the one draw back is the lack of support for the PlotSquared plugin.

**Comment by Ktar5** [comment]
Will check this out in the new update

**Comment by pixar02** [comment]
This has been added in the Recode in the form of an expansion for PlaceholderAPI.
New IBR version: bit.ly/InfoBoardReborn_bukkit
