### ISSUE TITLE
Infoboard 1.9

### ISSUE THREAD

**Issue by anhead** [Ktar5/Info-Board#89]
Hi I was wondering if you will update infoboardreborn to 1.9?

**Comment by ThemInspectors** [comment]
Well
 someone needs to fork it

**Comment by Ktar5** [comment]
^

**Comment by ThemInspectors** [comment]
Will placeholder API support  be added?

**Comment by Ktar5** [comment]
Yes

**Comment by antoniobenedetti** [comment]
@Ktar5 Can you please compile 1.9 jar? I need it badly. Even if it was buggy or early build, i just need it working on 1.9.

**Comment by pixar02** [comment]
https://www.spigotmc.org/resources/infoboardreloaded.44270/
