### ISSUE TITLE
Board Not Showing Up

### ISSUE THREAD

**Issue by SinisterXylene** [Ktar5/Info-Board#9]
Hi, i love your plugin and all its compatibility however there is an issue, my customized board doesnt show up to any player.
Here is my board config:
http://pastebin.com/gQiHxFeM
Here is my latest log:
http://pastebin.com/G3J2ZXhZ

**Comment by jessee55** [comment]
Hi i dont know if i can reply or something, but i have the same problem. Some variables dont work like for me <esstprequest> didnt work. i suggest u wait for an update that fixes the variables and adds a good api.

**Comment by Ktar5** [comment]
I stopped supporting the updates to plugin variables, I'm going to leave that to the plugin devs themselves once I get this api fleshed out
