### ISSUE TITLE
Support Tokenmanager

### ISSUE THREAD

**Issue by SK0RPI0NHD** [Ktar5/Info-Board#92]
Hello,
can you maybe to create variables for Tokenmanager ?I love your Plugin but i have a server which use Tokenmanager !

**Comment by pixar02** [comment]
It is supported by PlaceHolderAPI... So if you get the correct expansion you can have Tokenmanager palceholders... (use this version for IBR: [bit.ly/InfoBoardReloaded](bit.ly/InfoBoardReloaded) )
