### ISSUE TITLE
Infoboard compatible with Faction 2.5.0

### ISSUE THREAD

**Issue by ItsSilentShot** [Ktar5/Info-Board#93]
- Factions
  2.5.0 is widely used and we have that on our server. Please make it so that 1.7 or 1.8 doesn't matter can recognize variables from Factions 2.5.0. That would make my day, I have been looking for a good scoreboard/infoboard plugin for ages and I have found a great one, but please make it compatible with 2.5.0 It has got to be simple just please, don't leave 110k possible downloaders out. (One being me)

**Comment by pixar02** [comment]
this one supports it!
[bit.ly/InfoBoardReloaded](bit.ly/InfoBoardReloaded)
